config/routes.rb
Rails.application.routes.draw do
  root "static#index"

  resources :admins, only: [:index]

  get '/search', to: 'admins#search'
  post '/search', to: 'admins#foursquare'

  get '/gitsearch', to: 'admins#gitsearch'
  post '/github', to: 'admins#github'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    render layout: "admin"
  end

  def search
  end

  def foursquare
    begin
      @resp = Faraday.get 'https://api.foursquare.com/v2/venues/search' do |req|
        req.params['client_id'] = ''
        req.params['client_secret'] = ''
        req.params['v'] = '20160201'
        req.params['near'] = params[:zipcode]
        req.params['query'] = 'coffee shop'
      end

      body = JSON.parse(@resp.body)
      if @resp.success?
        @venues = body["response"]["venues"]
      else
        @error = body["meta"]["errorDetail"]
      end
    rescue Faraday::ConnectionFailed
      @error = "There was a timeout. Please try again."
    end
    render :search
  end

  def gitsearch
  end

  def github
    begin
      @resp = Faraday.get 'https://api.github.com/search/repositories' do |req| 
        req.params['q'] = params[:query]
        req.params['client_id'] = ''
        req.params['client_secret'] = ''      
      end

      body = JSON.parse(@resp.body)

      if @resp.success?
        @repos = body["items"]
      else
        @error = body["errors"]
      end
    rescue Faraday::ConnectionFailed
      @error = "There was a timeout. Please try again."
    end
    render :gitsearch
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/gitsearch.html.erb
<div class="row">
  <div class="col s12">  
    <h4>Git Search</h4>
  </div>
</div>

<div class="row">
  <div class="col s12">  
    <%= form_tag "/github" do %>  
      <div class="row">
        <div class="input-field col s12">
          <%= text_field_tag :query %>
          <%= label_tag :query %>
        </div>
      </div>
      <div class="row">
        <%= submit_tag "Search!", class: "btn waves-effect waves-light" %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <% if @error %>
      <p><%= @error %></p>
    <% elsif @repos %>
      <ul>
        <% @repos.each do |repo| %>
          <li>
            <strong>Name:</strong> <%= repo["name"] %><br>
            <strong>Description:</strong> <%= repo["description"] %>
            <hr>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/admins/index.html.erb
<div class="row">
  <div class="col s12">
    <h5>Admin</h5>
    <p>page for admin user information</p>
  </div>
</div>

app/views/admins/search.html.erb
<div class="row">
  <div class="col s12">  
    <%= form_tag "/search" do %>  
      <div class="row">
        <div class="input-field col s12">
          <%= text_field_tag :zipcode %>
          <%= label_tag :zipcode %>
        </div>
      </div>
      <div class="row">
        <%= submit_tag "Search!", class: "btn waves-effect waves-light" %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <% if @error %>
      <p><%= @error %></p>
    <% elsif @venues %>
      <ul>
        <% @venues.each do |venue| %>
          <li>
            <%= venue["name"] %><br>
            <%= venue["location"]["address"] %><br>
            Checkins: <%= venue["stats"]["checkinsCount"] %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">Logo</a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Admin", admins_path %></li>
      <li><%= link_to "Search", search_path %></li>
      <li><%= link_to "Git Search", gitsearch_path %></li>
      <li><a href="#">Mobile</a></li>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <li><%= link_to "Admin", admins_path %></li>
  <li><%= link_to "Search", search_path %></li>
  <li><%= link_to "Git Search", gitsearch_path %></li>
  <li><a href="#">Mobile</a></li>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeJune2019RailsJavascript</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navigation"%>

    <div class="row">
      <div class="col s12">
      </div>
    </div>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeJune2019RailsJavascript</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>